name: Haris Subandie MS
bio: 'A geek, friend and father.'
picture: 'assets/images/profile.png'

url: http://tedbundyjr.github.io
# your url: http://USERNAME.github.io
permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics: 'UA-74079520-1'
# disqus: mydisqus
facebook: tedbundyjr
twitter: tedbundyjr
instagram: tedbundyjr
# linkedin: tedbundyjr
youtube: tedbundyjr
spotify: tedbundyjr
github: tedbundyjr
email: ted@vms.my

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false

# if you don't need about or blog, comment them out below
about: true
blog: false

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
